@StoreAPI_HostAddress = http://localhost:5134/api

@AuthAPI_HostAddress = http://localhost:5134/api/Authenticate

@access_token = {{auth_login.response.body.accessToken}}
@refresh_token = {{auth_login.response.body.refreshToken}}

//@createdAt = {{$datetime iso8601}}
//@createdAt = {{$timestamp iso8601}}
@createdAt ={{$datetime 'YYYY-MM-DDTHH:mm:ss' 7 h}}
//@createdAt ={{$datetime rfc1123 7 h}}


#2012-04-23T18:25:43.511Z



### [Auth] Register
POST {{AuthAPI_HostAddress}}/register
Content-Type: application/json

{
  "username": "pingkunga1",
  "email": "pingkunga@gmail.com",
  "password": "As@1234",
  "firstName": "Pingkung",
  "lastName": "A"
}

### [Auth] Register Admin
POST {{AuthAPI_HostAddress}}/register-manager
Content-Type: application/json

{
  "username": "pingkung_manager",
  "email": "pingkungadm@gmail.com",
  "password": "Admin@1234",
  "firstName": "Pingkung",
  "lastName": "Admin"
}

### [Auth] Register Admin
POST {{AuthAPI_HostAddress}}/register-admin
Content-Type: application/json

{
  "username": "pingkungadmin",
  "email": "pingkungadmc@gmail.com",
  "password": "Admin@1234",
  "firstName": "Pingkung",
  "lastName": "Admin"
}

### [Auth] Login 
# @name auth_login
POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "pingkunga1",
  "password": "As@1234"
}

### [Auth] Login Manager
POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "pingkung_manager",
  "password": "Admin@1234"
}


### [Auth] Login Admin
POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "pingkungadmin",
  "password": "Admin@1234"
}

### [Auth] Logout
POST {{AuthAPI_HostAddress}}/logout
Content-Type: application/json


### Weather
GET {{StoreAPI_HostAddress}}/weatherforecast
Accept: application/json

### Test Connection
GET {{StoreAPI_HostAddress}}/product/testConnection
Accept: application/json

######################################################
############ CRUD
######################################################
### Get All Products
GET {{StoreAPI_HostAddress}}/product
Authorization: Bearer {{access_token}}
Accept: application/json

### Get All Products with Pagination
GET {{StoreAPI_HostAddress}}/product?page=1&pageSize=2
Authorization: Bearer {{access_token}}
Accept: application/json

### Get All Products with search
GET {{StoreAPI_HostAddress}}/product?searchCategory=1
Authorization: Bearer {{access_token}}
Accept: application/json

### Get All Products with String search
GET {{StoreAPI_HostAddress}}/product?searchQuery=iP
Authorization: Bearer {{access_token}}
Accept: application/json

### Get All Products with String search
GET {{StoreAPI_HostAddress}}/product?page=1&pageSize=1&searchCategory=1&searchQuery=iP
Authorization: Bearer {{access_token}}
Accept: application/json


### Get Product By Id
GET {{StoreAPI_HostAddress}}/product/1
Authorization: Bearer {{access_token}}
Accept: application/json

# ### Add new product
# POST {{StoreAPI_HostAddress}}/product
# Content-Type: application/json
# Accept: application/json

# {
#   "category_id": 1,
#   "product_name": "Mobile Product New",
#   "unit_price": 10,
#   "product_picture": "https://www.popticles.com/wp-content/uploads/2021/04/iphone-410311_1280-1024x682.jpg",
#   "unit_in_stock": 100,
#   "created_date": "2021-07-01T00:00:00",
#   "modified_date": "2021-07-01T00:00:00"
# }

### Multi-Part Exam-le
https://stackoverflow.com/questions/61473990/how-to-post-an-image-with-form-data-in-rest-client-for-vscode


### Create a new product with file upload (Multi-Part Exam)
POST {{StoreAPI_HostAddress}}/Product 
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_id" 

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id" 

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_name" 

Xiaomi 13T Pro
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_price" 

17490
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_in_stock"

100
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="created_date" 

{{createdAt}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="modified_date" 




------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="xiaomi13TPro.jpg" 
Content-Type: image/jpeg 

< ./test_images/xiaomi13TPro.jpg 
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#------WebKitFormBoundary7MA4YWxkTrZu0gW
#Content-Disposition: form-data; name="category.category_id" 

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="category.category_name"

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="category.category_status"


### Update product
PUT {{StoreAPI_HostAddress}}/product/16
Content-Type: application/json
Accept: application/json

{
  "product_id": 16,
  "category_id": 1,
  "product_name": "Mobile Product Updated",
  "unit_price": 20,
  "product_picture": "https://www.popticles.com/wp-content/uploads/2021/04/iphone-410311_1280-1024x682.jpg",
  "unit_in_stock": 200,
  "created_date": "2021-07-01T00:00:00",
  "modified_date": "2021-07-01T00:00:00"
}


### Delete product
DELETE {{StoreAPI_HostAddress}}/product/15
Accept: application/json

``` 


### Get All Categories
GET {{StoreAPI_HostAddress}}/category
Authorization : Bearer {{access_token}}
Accept: application/json


